export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const SET_USERS_DETAILS = 'SET_USERS_DETAILS';
export const CLEAN_HISTORY_DATA = 'CLEAN_HISTORY_DATA';
export const USER_SOCIAL_LOGIN_SUCCESS = 'USER_SOCIAL_LOGIN_SUCCESS';